name = "KrigingEstimators"
uuid = "d293930c-a38c-56c5-8ebb-12008647b47a"
author = "JÃºlio Hoffimann <julio.hoffimann@gmail.com>"
version = "0.7.5"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
GeoStatsBase = "323cb8eb-fbf6-51c0-afd0-f8fba70507b2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Variography = "04a0146e-e6df-5636-8d7f-62fa9eb0b20c"

[compat]
Combinatorics = "0.7, 1.0"
GeoStatsBase = "0.21"
Meshes = "0.16"
Variography = "0.12"
julia = "1.5"
