name = "KrigingEstimators"
uuid = "d293930c-a38c-56c5-8ebb-12008647b47a"
author = "Júlio Hoffimann <julio.hoffimann@gmail.com>"
version = "0.2.2"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Variography = "04a0146e-e6df-5636-8d7f-62fa9eb0b20c"

[extras]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Pkg", "Random", "Test"]

[compat]
Variography = "≥ 0.3.6"
julia = "1"
